leancodepl/flutter_corelibrary

packages/cqrs/CHANGELOG.md
packages/cqrs/LICENSE
packages/cqrs/lib/src/command_result.dart
packages/cqrs/pubspec.yaml
packages/cqrs/test/command_result_test.dart

- Add `success` and `failed` constructors in `CommandResult`.
- Add `failed` getter in `CommandResult`.
- Make `success` field in `CommandResult` a getter. This is compatible with how [the backend works](https://github.com/leancodepl/corelibrary/blob/a3a2a27b20e1cf684fb88aa55958721eff19c2bc/src/Domain/LeanCode.CQRS/CommandResult.cs#L11).
- Deprecate `success` param in `CommandResult` constructor.

Add success and failed constructors to CommandResult

---

packages/login_client/CHANGELOG.md
packages/login_client/analysis_options.yaml
packages/login_client/lib/login_client.dart
packages/login_client/lib/src/login_client.dart
packages/login_client/lib/src/oauth_settings.dart
packages/login_client/pubspec.yaml
packages/login_client/test/login_client_test.dart
packages/login_client_flutter/CHANGELOG.md
packages/login_client_flutter/lib/src/flutter_secure_credentials_storage.dart
packages/login_client_flutter/pubspec.yaml

After using this library in a production app, there were few issues discovered. This Pull Request fixes them.
Also, I went back to the `onCredentialsChanged` stream in the `LoginClient` class as it was in the 0.* versions of the login_client library. It's just much easier for the developer and cleaner to use stream instead of passing a callback that the developer would have to prospectively somehow reach from other parts of the code.
**login_client**
- OAauth2 `clientId` and `clientSecret` now default to an empty string.
- Export `oauth2` `Credentials`, `AuthorizationException` and `ExpirationException`.
- Add `onCredentialsChanged` stream to `LoginClient`.
- Deprecate `credentialsChangedCallback`.
**login_client_flutter**
- Fix reading null credentials.
Closes #11.

login_client improvements

---

packages/login_client/CHANGELOG.md
packages/login_client/pubspec.yaml

> Because login_client >=2.0.0 depends on meta ^1.4.0 and every version of flutter from sdk depends on meta 1.3.0, login_client >=2.0.0 is incompatible with flutter from sdk.

Downgrade login_client's meta dependency

---

packages/login_client/CHANGELOG.md
packages/login_client/lib/src/login_client.dart
packages/login_client/pubspec.yaml

Fix closing the OAuthClient, that the only thing it does is closing the inner HTTP client (that is the same as the one we use for unauthorized users). https://github.com/dart-lang/oauth2/blob/master/lib/src/client.dart#L184
CC @FlowerAlex

[login_client] Fix closing default HTTP client after logging out.

---

.github/workflows/override_api_endpoint-publish.yml
.github/workflows/override_api_endpoint-test.yml
README.md
packages/override_api_endpoint/.gitignore
packages/override_api_endpoint/.metadata
packages/override_api_endpoint/CHANGELOG.md
packages/override_api_endpoint/LICENSE
packages/override_api_endpoint/README.md
packages/override_api_endpoint/analysis_options.yaml
packages/override_api_endpoint/lib/override_api_endpoint.dart
packages/override_api_endpoint/lib/src/override_api_endpoint.dart
packages/override_api_endpoint/pubspec.yaml

So this is basically the feature requested by @jakubfijalkowski that will allow backend devs to use test builds with local (dev) backend. To override endpoint you need to launch app with correctly set up deeplink. The endpoint is persisted using `SharedPreferences`.

Introduce override_api_endpoint package

---

packages/login_client_flutter/CHANGELOG.md
packages/login_client_flutter/pubspec.yaml

Actually closes #31 
As far as I can tell the API has not changed, tested 4.2.0 and 5.0.0 and both seem to work.

Increase flutter_secure_storage version range

---

packages/leancode_lint/CHANGELOG.md
packages/leancode_lint/README.md
packages/leancode_lint/lib/analysis_options.yaml
packages/leancode_lint/pubspec.yaml

- disable unwanted lints
- update version
Also removed part of docs talking about Dart <2.14, which we don't support.

Disable 2 lints that we don't want

---

packages/leancode_lint/CHANGELOG.md
packages/leancode_lint/lib/leancode_lint.dart
packages/leancode_lint/lib/src/unawaited.dart

Minimum Dart SDK version of `leancode_lint` is `2.17.0`, and `unawaited()` has been in Dart's stdlib since Dart 2.14.
See also:
- [unawaited function API reference](https://api.dart.dev/stable/dart-async/unawaited.html)

Remove the `unawaited()` function

---

packages/leancode_lint/CHANGELOG.md
packages/leancode_lint/pubspec.yaml

Not sure what version to choose.
This can be potentially breaking if someone was depending on `unawaited()` from `package:leancode_lint`. They'll have to use `unawaited()` from `dart:async` instead.

leancode_lint: bump version

---

.github/workflows/leancode_hooks-test.yml
.github/workflows/login_client_flutter-test.yml
.github/workflows/override_api_endpoint-test.yml
README.md
codecov.yml
packages/cqrs/CHANGELOG.md
packages/cqrs/README.md
packages/cqrs/pubspec.yaml
packages/leancode_hooks/CHANGELOG.md
packages/leancode_hooks/README.md
packages/leancode_hooks/pubspec.yaml
packages/login_client/CHANGELOG.md
packages/login_client/README.md
packages/login_client/pubspec.yaml
packages/login_client_flutter/CHANGELOG.md
packages/login_client_flutter/README.md
packages/login_client_flutter/pubspec.yaml
packages/override_api_endpoint/CHANGELOG.md
packages/override_api_endpoint/README.md
packages/override_api_endpoint/pubspec.yaml

* Fixed build badges in packages READMEs and in main README
* Instead of `beta` and `stable` channels, explicit latest stable version (3.3) is used in CI
* Make Codecov informational, so it won't fail the CI

Fix README build badges

---

packages/leancode_lint/CHANGELOG.md
packages/leancode_lint/lib/analysis_options.yaml
packages/leancode_lint/pubspec.yaml

`implicit_call_tearoffs` and `unreachable_from_main` did not gain enough positive votes, and thus are not enabled.
closes #80

Enable new dart 2.19 lints

---

packages/leancode_lint/CHANGELOG.md
packages/leancode_lint/lib/analysis_options.yaml
packages/leancode_lint/lib/analysis_options_package.yaml
packages/leancode_lint/pubspec.yaml

It got added by accident when removing `flutter_lints`

Remove library_private_types_in_public_api

---

packages/leancode_hooks/CHANGELOG.md
packages/leancode_hooks/lib/src/use_post_frame_effect.dart
packages/leancode_hooks/pubspec.yaml
packages/leancode_hooks/test/use_post_frame_effect_test.dart

usePostFrameEffect should accept nullable keys just as the original useEffect does

Make usePostFrameEffect accept nullable keys

---

.github/workflows/cqrs-publish.yml
.github/workflows/cqrs-test.yml
.github/workflows/login_client-publish.yml
.github/workflows/login_client-test.yml
packages/cqrs/CHANGELOG.md
packages/cqrs/pubspec.yaml
packages/login_client/CHANGELOG.md
packages/login_client/lib/login_client.dart
packages/login_client/pubspec.yaml
packages/login_client/test/login_client_test.dart
packages/login_client/test/login_client_test.mocks.dart

Since we are requiring dart 3 here, maybe it is worth revisiting the API to modernize for records/class modifiers?

Bump package:http to v1 in packages

---

packages/leancode_analytics/README.md
packages/leancode_analytics/lib/core/event.dart
packages/leancode_analytics/pubspec.yaml

As in the title. We change the approach for passing analytics id key. Required to add analytics to leancode_flutter_template

TapAnalyticsEvent need String instead of ValueKey

---

packages/cqrs/CHANGELOG.md
packages/cqrs/lib/cqrs.dart
packages/cqrs/lib/src/command_response.dart
packages/cqrs/lib/src/cqrs.dart
packages/cqrs/lib/src/cqrs_error.dart
packages/cqrs/lib/src/cqrs_result.dart
packages/cqrs/pubspec.yaml
packages/cqrs/test/command_response_test.dart
packages/cqrs/test/cqrs_middleware_test.dart
packages/cqrs/test/cqrs_result_test.dart
packages/cqrs/test/cqrs_test.dart

- Rename `forbiddenAccess` to `authorization` in error enums.
- Update error enums docs.
- Fix `CqrsMiddleware` not being exported from the package.
- Move `hasError` and `hasErrorForProperty` from `CommandResponse` to `CommandFailure`.

Fix cqrs v10.0.0 issues

---

packages/leancode_flutter_svg_adaptive_loader/CHANGELOG.md
packages/leancode_flutter_svg_adaptive_loader/lib/src/compute.dart
packages/leancode_flutter_svg_adaptive_loader/lib/src/leancode_flutter_svg_adaptive_loader.dart
packages/leancode_flutter_svg_adaptive_loader/pubspec.yaml

The fact that `compute` spawns isolates in debug mode caused massive drops in performance related to `.svg` assets loading. When I had a tens of assets in the same view, it took ~5s to load all of them using `FlutterSvgAdaptiveLoader`. That was approx 10x worse than using `SvgAssetLoader` from `flutter_svg`. 
For that reason I brought more optimised `compute` implementation for debug mode from `flutter_svg` package. It seems that this version of `compute` solves performance issues.

Add compute implementation from `flutter_svg` that does not spawn isolates in debug mode

---

packages/leancode_flutter_svg_adaptive_loader/CHANGELOG.md
packages/leancode_flutter_svg_adaptive_loader/lib/src/leancode_flutter_svg_adaptive_loader.dart
packages/leancode_flutter_svg_adaptive_loader/pubspec.yaml

Former implementation of `FlutterSvgAdaptiveLoader.loadBytes` causes exception:
```
FlutterError (Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.)
```

Create cache key early to avoid resolving DefaultAssetBundle when ancestor is deactivated

---

packages/leancode_lint/CHANGELOG.md
packages/leancode_lint/README.md
packages/leancode_lint/pubspec.yaml

This is just an idea.
I'm a fan of leancode_lint and use it in my personal projects, and open-source ones I maintain(ed) (e.g. [`flutter_downloader`](https://github.com/fluttercommunity/flutter_downloader/blob/e1d96a777ccb394fee0c6e30bc99b12bd8be9456/pubspec.yaml#L28), [`location`](https://github.com/Lyokone/flutterlocation/blob/7cc54d74a5b53f8c6465ca0e4e5171b39fa49f8d/packages/location/pubspec.yaml#L35)). I think the current description is not interesting for outsiders, but it should be. These lint rules are real good.

Make README more appealing to non-LeanCoders

---

.github/workflows/leancode_lint-publish.yml
.github/workflows/leancode_lint-test.yml
packages/leancode_lint/CHANGELOG.md
packages/leancode_lint/lib/analysis_options.yaml
packages/leancode_lint/lib/lints/constructor_parameters_and_fields_should_have_the_same_order.dart
packages/leancode_lint/pubspec.yaml

Disables a few lints that were deprecated or removed for the 3.3.0 Dart release. Also bumps the SDK to that version.

Disable deprecated 3.3.0 lints

---

packages/leancode_lint/CHANGELOG.md
packages/leancode_lint/README.md
packages/leancode_lint/lib/analysis_options.yaml
packages/leancode_lint/pubspec.yaml
packages/leancode_lint/test/lints_test_app/pubspec.lock
packages/leancode_lint/test/lints_test_app/pubspec.yaml

Removes the reference to `import_of_legacy_library_into_null_safe` (Will have been removed in Dart 3.4.0 via https://github.com/dart-lang/sdk/commit/14a9782895762056dc0d705bf0253817bb2ac37c, but it was already deprecated)

Remove legacy lints

---

packages/leancode_lint/lib/lints/constructor_parameters_and_fields_should_have_the_same_order.dart
packages/leancode_lint/test/lints_test_app/lib/constructor_parameters_and_fields_should_have_the_same_order_test.dart

Changes how `constructor_parameters_and_fields_should_have_the_same_order` reports issues.
Right now the issue is reported just above the first parameter, which doesn't always cause the problem. In my opinion it would be better if the lint reported issues above the constructor.
This is especially confusing when one wants to use `ignore`:
How it looks now:
```
class MyClass{
MyClass({
// ignore: constructor_parameters_and_fields_should_have_the_same_order
required this.value,
required this.label,
required this.enabled,
});
final bool enabled;
final double value;
final String label;
}
```
How it looks after my changes:
```
class MyClass{
// ignore: constructor_parameters_and_fields_should_have_the_same_order
MyClass({
required this.value,
required this.label,
required this.enabled,
}); …
```

Change diagnostic location for `constructor_parameters_and_fields_should_have_the_same_order`

---

packages/login_client/CHANGELOG.md
packages/login_client/lib/src/login_client.dart
packages/login_client/lib/src/utils.dart
packages/login_client/pubspec.yaml
packages/login_client/test/login_client_test.dart

Always set `tokenEndpoint` using value of `authorizationUri` from `OAuthSettings` during `LoginClient` initialization.

---

.github/workflows/leancode_lint-publish.yml
.github/workflows/leancode_lint-test.yml
packages/leancode_lint/CHANGELOG.md
packages/leancode_lint/lib/lints/add_cubit_suffix_for_cubits.dart
packages/leancode_lint/lib/lints/avoid_conditional_hooks.dart
packages/leancode_lint/lib/lints/avoid_single_child_in_multi_child_widget.dart
packages/leancode_lint/lib/lints/catch_parameter_names.dart
packages/leancode_lint/lib/lints/constructor_parameters_and_fields_should_have_the_same_order.dart
packages/leancode_lint/lib/lints/hook_widget_does_not_use_hooks.dart
packages/leancode_lint/lib/lints/prefix_widgets_returning_slivers.dart
packages/leancode_lint/lib/lints/start_comments_with_space.dart
packages/leancode_lint/lib/lints/use_instead_type.dart
packages/leancode_lint/pubspec.yaml
packages/leancode_lint/test/lints_test_app/pubspec.lock
packages/leancode_lint/test/lints_test_app/pubspec.yaml

- Closes #394
- `package:analyzer` went back to exporting its own `LintCode`, so it has to be hidden again

Support Dart 3.6

---

.github/workflows/leancode_debug_page-publish.yml
.github/workflows/leancode_debug_page-test.yml
packages/leancode_debug_page/CHANGELOG.md
packages/leancode_debug_page/README.md
packages/leancode_debug_page/example/pubspec.lock
packages/leancode_debug_page/pubspec.yaml
packages/leancode_debug_page/test/logging_http_client_test.dart

Changes required to upgrade flutter version in [template app](https://github.com/leancodepl/leancode_flutter_template), specifically upgrade of rxdart to 0.28.0 was needed which caused the necessity to upgrade:
- leancode_lint to 14.0.0 (which requires raising min dart sdk version to 3.5.0)
summing up 
- rx_dart: ^0.27.7 -> ^0.28.0
- leancode_lint: 13.0.0 -> 14.0.0
- min dart sdk: -> 3.5.0
- dart sdk version in testing workflows adjusted accordingly
Please let me know about the approach taken here. For now in [pr upgrading flutter in template](https://github.com/leancodepl/leancode_flutter_template/pull/340) i'm using ref from the last commit in this branch as dependency; previously it was imported as package. Should there be new release planned or should we stick to getting package from …

Upgrade rxdart in debug_page

---

packages/enhanced_gradients/CHANGELOG.md
packages/enhanced_gradients/pubspec.yaml

I didn't notice that 2.0.0 wasn't ever released, so I would change the version number back to 2.0.0 and release it this time.

Change version number from 3.0.0 to 2.0.0

---

.github/workflows/force_update-publish.yml
.github/workflows/force_update-test.yml
README.md
packages/force_update/README.md
packages/force_update/pubspec.yaml

I've sorted packages in README alphabetically, I hope that's okay.  I suggest ignoring this commit when reviewing.

[LMG-109] Publish force update

---

packages/cqrs/CHANGELOG.md
packages/cqrs/lib/cqrs.dart
packages/cqrs/pubspec.yaml

`CommandResponse` (formerly `CommandResult`) is used in contracts, so it has to be accessible from outside of this package ([docs](https://github.com/leancodepl/contractsgenerator/blob/f3f2d112f4368f9616e4e7a9e5b90950db25a35b/docs/types.md)).

Make CommandResponse public

---

packages/override_api_endpoint/CHANGELOG.md
packages/override_api_endpoint/lib/src/override_api_endpoint.dart
packages/override_api_endpoint/pubspec.yaml

Previous implementation was clearing API endpoint saved in shared preferences if it was not provided explicity. This makes configuring more than one override endpoint within the app. 
This PR makes clearing the value in shared preferences explicit, allowing to configure multiple urls within the same app.

Improve clearing the API endpoint
