leancodepl/flutter_corelibrary

codecov.yml, packages/cqrs/lib/contracts.dart, packages/cqrs/lib/cqrs.dart, packages/cqrs/lib/src/contract_types.dart, packages/cqrs/lib/src/cqrs.dart, packages/cqrs/lib/src/cqrs_exception.dart, packages/cqrs/lib/src/transport_types.dart, packages/login_client/LICENSE, packages/login_client/lib/login_client.dart, packages/login_client/lib/src/credentials_storage/credentials_storage.dart, packages/login_client/lib/src/credentials_storage/in_memory_credentials_storage.dart, packages/login_client/lib/src/login_client.dart, packages/login_client/lib/src/oauth2/custom_grant.dart, packages/login_client/lib/src/oauth_settings.dart, packages/login_client/lib/src/refresh_exception.dart, packages/login_client/lib/src/strategies/authorization_strategy.dart, packages/login_client/lib/src/strategies/client_credentials_strategy.dart, packages/login_client/lib/src/strategies/custom_grant_strategy.dart, packages/login_client/lib/src/strategies/raw_credentials_strategy.dart, packages/login_client/lib/src/strategies/resource_owner_password_strategy.dart, packages/login_client/lib/src/strategies/sms_token_strategy.dart, packages/login_client/lib/src/utils.dart, packages/login_client_flutter/LICENSE, packages/login_client_flutter/lib/login_client_flutter.dart, packages/login_client_flutter/lib/src/flutter_secure_credentials_storage.dart
Enable carryforward option for Codecov so that the coverages are correct for each project in our monorepo.
Also, to trigger workflows for each project I updated the year in copyright comments in each file :)
=> Codecov carryforward configuration

packages/cqrs/CHANGELOG.md, packages/cqrs/lib/src/cqrs.dart, packages/cqrs/pubspec.yaml, packages/cqrs/test/cqrs_test.dart
Related to https://github.com/leancodepl/corelibrary/issues/193.
=> Fix for null query results

codecov.yml, packages/login_client/CHANGELOG.md, packages/login_client/lib/src/login_client.dart, packages/login_client/pubspec.yaml
=> Remove closing http client after logging out

packages/cqrs/CHANGELOG.md, packages/cqrs/lib/src/command_result.dart, packages/cqrs/pubspec.yaml, packages/cqrs/test/command_result_test.dart, packages/cqrs/test/validation_error_test.dart
I'm not sure what's the version we finally want to go with, as technically it's a breaking change I bumped it to 5.0.0.
=> Add propertyName to ValidationError

.github/workflows/login_client_flutter-publish.yml, .github/workflows/login_client_flutter-test.yml, packages/login_client_flutter/CHANGELOG.md, packages/login_client_flutter/lib/src/flutter_secure_credentials_storage.dart, packages/login_client_flutter/pubspec.yaml
=> Migrate login_client_flutter to null-safety

packages/login_client/lib/src/login_client.dart, packages/login_client/test/login_client_test.dart
Related issue: https://github.com/dart-lang/oauth2/issues/119
=> Call refresh() if the first response is 401

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/README.md, packages/leancode_lint/pubspec.yaml
I found it a bit unclear, so googled a bit and added an explanation that would have satisfied me and not require any googling.
=> Improve `leancode_lint` readme

.prettierrc, packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/README.md, packages/leancode_lint/pubspec.yaml
=> Remove `leancode_lint`'s dependency on `flutter`

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/pubspec.yaml
Forgot to do it in the previous PR
=> Bump leancode_lint version

packages/override_api_endpoint/README.md, packages/override_api_endpoint/pubspec.yaml
=> Update README usage section

packages/leancode_hooks/pubspec.yaml
=> set leancode_hooks version to 0.0.2 in its pubspec

.github/workflows/leancode_hooks-test.yml, .github/workflows/login_client_flutter-test.yml, .github/workflows/override_api_endpoint-test.yml, packages/leancode_hooks/CHANGELOG.md, packages/leancode_hooks/README.md, packages/leancode_hooks/lib/src/use_decarative_text_editing_controller.dart, packages/leancode_hooks/lib/src/use_focused.dart, packages/leancode_hooks/lib/src/use_post_frame_effect.dart, packages/leancode_hooks/lib/src/use_synced_text_editing_controller.dart, packages/leancode_hooks/pubspec.yaml, packages/leancode_hooks/test/use_throttle_test.dart
- fix link in flutter_hooks readme
- fix leancode_hooks CHANGELOG links
- start adding tests for hooks (only for `useThrottle` for now)
=> `leancode_hooks` improvements

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/analysis_options.yaml, packages/leancode_lint/pubspec.yaml
=> Add new lints from Dart 2.17

.github/workflows/leancode_hooks-test.yml, .github/workflows/login_client-test.yml, .github/workflows/login_client_flutter-test.yml, .github/workflows/override_api_endpoint-test.yml
=> Fix tags-ignore

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/analysis_options.yaml, packages/leancode_lint/pubspec.yaml
=> Enable new dart 2.18 lints 

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/analysis_options.yaml
=> Remove `invariant_booleans` lint

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/analysis_options.yaml
=> Remove `discarded_futures` lint

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/pubspec.yaml
=> leancode_lint - fix broken changelog

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/analysis_options.yaml, packages/leancode_lint/pubspec.yaml
=> Replace strong mode with language features

.github/workflows/leancode_lint-publish.yml, packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/analysis_options.yaml, packages/leancode_lint/pubspec.yaml
=> Enable dart 3 lints

packages/leancode_hooks/CHANGELOG.md, packages/leancode_hooks/lib/leancode_hooks.dart, packages/leancode_hooks/lib/src/use_bloc.dart, packages/leancode_hooks/lib/src/use_bloc_listener.dart, packages/leancode_hooks/lib/src/use_bloc_state.dart, packages/leancode_hooks/pubspec.yaml, packages/leancode_hooks/test/use_bloc_listener_test.dart, packages/leancode_hooks/test/use_bloc_state_test.dart
=> Implement useBlocState and useBlocListener hooks

packages/debug_page/lib/src/ui/debug_page_overlay.dart, packages/debug_page/pubspec.yaml
https://github.com/leancodepl/flutter_corelibrary/assets/61657553/467516ae-cca7-4684-84c6-fdf7d9a65eeb
=> Replace debug page's ugly button with nice draggable fab

.github/CODEOWNERS, .github/workflows/leancode_lint-publish.yml, .github/workflows/leancode_lint-test.yml, packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/analysis_options.yaml, packages/leancode_lint/pubspec.yaml
Waiting on the decision on what to do with `use_build_context_synchronously`.
closes #193
=> Enable Dart 3.2 lints

packages/login_client/CHANGELOG.md, packages/login_client/lib/src/login_client.dart, packages/login_client/pubspec.yaml, packages/login_client/test/login_client_test.dart
=> Add get credentials for LoginClient

.github/workflows/cqrs-publish.yml, .github/workflows/cqrs-test.yml, .github/workflows/leancode_flutter_svg_adaptive_loader-publish.yml, .github/workflows/leancode_flutter_svg_adaptive_loader-test.yml, .github/workflows/leancode_hooks-publish.yml, .github/workflows/leancode_hooks-test.yml, .github/workflows/login_client-publish.yml, .github/workflows/login_client-test.yml, .github/workflows/login_client_flutter-publish.yml, .github/workflows/login_client_flutter-test.yml, .github/workflows/override_api_endpoint-publish.yml, .github/workflows/override_api_endpoint-test.yml, packages/cqrs/CHANGELOG.md, packages/cqrs/pubspec.yaml, packages/debug_page/CHANGELOG.md, packages/debug_page/example/pubspec.lock, packages/debug_page/pubspec.yaml, packages/leancode_analytics/CHANGELOG.md, packages/leancode_analytics/pubspec.yaml, packages/leancode_flutter_svg_adaptive_loader/CHANGELOG.md, packages/leancode_flutter_svg_adaptive_loader/example/pubspec.lock, packages/leancode_flutter_svg_adaptive_loader/pubspec.yaml, packages/leancode_hooks/CHANGELOG.md, packages/leancode_hooks/pubspec.yaml, packages/login_client/CHANGELOG.md, packages/login_client/pubspec.yaml, packages/login_client_flutter/CHANGELOG.md, packages/login_client_flutter/pubspec.yaml, packages/override_api_endpoint/CHANGELOG.md, packages/override_api_endpoint/pubspec.yaml
Not adding changelog entries. This does not affect any downstream users.
=> Bump leancode_lint in all packages

packages/login_client_flutter/CHANGELOG.md, packages/login_client_flutter/pubspec.yaml
=> Bump flutter version and login_client dependency

.github/workflows/leancode_lint-publish.yml
=> Use mobile-tools for releasing leancode_lint

packages/leancode_lint/README.md
=> Document how to disable lints

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/lints/avoid_conditional_hooks.dart, packages/leancode_lint/test/lints_test_app/lib/avoid_conditional_hooks_test.dart, packages/leancode_lint/test/lints_test_app/pubspec.lock
=> Fix conditional hook in hook builder false positive

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/pubspec.yaml, packages/leancode_lint/test/lints_test_app/pubspec.lock, packages/leancode_lint/test/lints_test_app/pubspec.yaml
=> Bump custom_lint_builder in leancode_lint

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/helpers.dart, packages/leancode_lint/pubspec.yaml, packages/leancode_lint/test/lints_test_app/lib/avoid_conditional_hooks_test.dart, packages/leancode_lint/test/lints_test_app/lib/hook_widget_does_not_use_hooks_test.dart, packages/leancode_lint/test/lints_test_app/pubspec.lock
=> Treat HookWidget as a new hook context

packages/login_client/test/login_client_test.dart
I hadn't noticed this before merge :(
=> Remove unused import

.github/workflows/leancode_lint-publish.yml, .github/workflows/leancode_lint-test.yml, packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/analysis_options.yaml, packages/leancode_lint/lib/lints/add_cubit_suffix_for_cubits.dart, packages/leancode_lint/lib/lints/avoid_conditional_hooks.dart, packages/leancode_lint/lib/lints/avoid_single_child_in_multi_child_widget.dart, packages/leancode_lint/lib/lints/catch_parameter_names.dart, packages/leancode_lint/lib/lints/constructor_parameters_and_fields_should_have_the_same_order.dart, packages/leancode_lint/lib/lints/hook_widget_does_not_use_hooks.dart, packages/leancode_lint/lib/lints/prefix_widgets_returning_slivers.dart, packages/leancode_lint/lib/lints/start_comments_with_space.dart, packages/leancode_lint/lib/lints/use_instead_type.dart, packages/leancode_lint/pubspec.yaml, packages/leancode_lint/test/lints_test_app/lib/constructor_parameters_and_fields_should_have_the_same_order_test.dart, packages/leancode_lint/test/lints_test_app/lib/prefix_widgets_returning_slivers_test.dart, packages/leancode_lint/test/lints_test_app/lib/use_design_system_item_test.dart, packages/leancode_lint/test/lints_test_app/pubspec.lock, packages/leancode_lint/test/lints_test_app/pubspec.yaml
=> Enable dart 3.5 lints

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/lints/use_instead_type.dart, packages/leancode_lint/pubspec.yaml, packages/leancode_lint/test/lints_test_app/analysis_options.yaml, packages/leancode_lint/test/lints_test_app/lib/use_design_system_item_test.dart
=> Allow usage of a forbidden item in a hide combinator

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/analysis_options.yaml, packages/leancode_lint/pubspec.yaml
=> Remove `division_optimization` hint

packages/leancode_hooks/README.md
Added missing hooks to README.md
=> [`leancode_hooks`] Update README.md

packages/leancode_lint/CHANGELOG.md, packages/leancode_lint/lib/lints/add_cubit_suffix_for_cubits.dart, packages/leancode_lint/lib/lints/avoid_conditional_hooks.dart, packages/leancode_lint/lib/lints/avoid_single_child_in_multi_child_widget.dart, packages/leancode_lint/lib/lints/catch_parameter_names.dart, packages/leancode_lint/lib/lints/constructor_parameters_and_fields_should_have_the_same_order.dart, packages/leancode_lint/lib/lints/hook_widget_does_not_use_hooks.dart, packages/leancode_lint/lib/lints/prefix_widgets_returning_slivers.dart, packages/leancode_lint/lib/lints/start_comments_with_space.dart, packages/leancode_lint/lib/lints/use_instead_type.dart, packages/leancode_lint/pubspec.yaml, packages/leancode_lint/test/lints_test_app/pubspec.lock, packages/leancode_lint/test/lints_test_app/pubspec.yaml
=> Support custom lint ^0.7.0

.github/workflows/cqrs-test.yml, .github/workflows/leancode_flutter_svg_adaptive_loader-test.yml, .github/workflows/leancode_hooks-test.yml, .github/workflows/leancode_lint-test.yml, .github/workflows/leancode_markup-test.yml, .github/workflows/login_client-test.yml, .github/workflows/login_client_flutter-test.yml, .github/workflows/override_api_endpoint-test.yml, README.md
Also, add a missing build status badge for `leancode_lint` and fix an invalid ignore in `cqrs_test` workflow
=> Refactor caching in Flutter actions

packages/leancode_force_update/pubspec.yaml
That's for testing the publishing workflow
=> Bump leancode_force_update build metadata

packages/leancode_debug_page/CHANGELOG.md, packages/leancode_debug_page/lib/src/core/logging_http_client.dart, packages/leancode_debug_page/pubspec.yaml
Long response bodies were not read fully
=> [leancode_debug_page] Fix reading response body

packages/leancode_debug_page/CHANGELOG.md, packages/leancode_debug_page/example/android/app/build.gradle, packages/leancode_debug_page/example/android/build.gradle, packages/leancode_debug_page/example/android/gradle/wrapper/gradle-wrapper.properties, packages/leancode_debug_page/example/android/settings.gradle, packages/leancode_debug_page/example/pubspec.lock, packages/leancode_debug_page/lib/src/ui/debug_page_button.dart, packages/leancode_debug_page/pubspec.yaml
=> [leancode_debug_page] Fix debug page on web
